### PR TITLE
Infrastructure additions/changes for generated GH documentation

### PR DESCRIPTION
**Pull request by stulees**
- Accounting for repo name change in bower and package files
- Moving demo files into new demo/ directory
- Adding necessary `index.html` file for generating GH page
- Adding documentation to `rise-google-sheet.html` for generated GH page

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
:+1:

**Comment by stulees** [comment]
@donnapep I've changed the repo name back to its original and adjusted this PR accordingly. Can you do a quick review again, cheers.

**Comment by donnapep** [comment]
@stulees Not sure I would change it back just yet. I haven't been able to get rise-page to work.

**Pull request merged**
